name: test-concordia

on:
  push:
    branches:
      - main
    paths:
      - '.github/actions/install-concordia/action.yml'
      - '.github/workflows/test-concordia.yml'
      - '.pylintrc'
      - 'concordia/**'
      - 'pyproject.toml'
      - 'setup.py'
  pull_request:
    branches:
      - main
    paths:
      - '.github/actions/install-concordia/action.yml'
      - '.github/workflows/test-concordia.yml'
      - '.pylintrc'
      - 'concordia/**'
      - 'pyproject.toml'
      - 'setup.py'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  test-concordia:
    name: Test Concordia
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Concordia
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Install Concordia
        uses: ./.github/actions/install-concordia

      - name: Test Concordia
        run: pytest concordia

      - name: Lint Concordia
        run: pylint --errors-only concordia

      - name: Typecheck Concordia
        run: pytype concordia
